clean2:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS)
	-$(RM) $(OBJS) *.elf
	-@echo ' '

*.elf: $(wildcard ..E:/11_code/16_sk/20_ck-hpm6750_code/01_6750_boot/hpm6750_boot/board/linker_scripts/flash_rtt.ld)
